import Head from "next/head";
import React from "react";
import PeopleGrid from "../components/PeopleGrid";

const Intro = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PeopleGrid />
      <section className="wot neu-01 noSpacingTop">
        <div className="wot__wrapper">
          <div className="wot__heading">
            <h2 className="wot__title dark:text-blue-400">Member</h2>
            <h3 className="wot__subtitle dark:text-slate-200">
              Lorem, ipsum dolor.
            </h3>
          </div>
          <div className="wot__text">
            <p>CTO</p>
            <h2 className="wot__title dark:text-blue-400">Member</h2>
            <h3 className="wot__subtitle noSpacingBottom dark:text-slate-200">
              Lorem ipsum dolor sit amet.
            </h3>
          </div>
        </div>
      </section>
    </>
  );
};

export default Intro;
