import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { userRequest } from "../requestMethods";

const Register = () => {
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await userRequest.post("/auth/register", {
        username,
        email,
        password,
      });
      res.data && window.location.replace("/login");
    } catch (err) {
      setError(true);
      setTimeout(() => {
        setError(false);
      }, 1000);
    }
  };

  return (
    <>
      <Head>
        <title>Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="register">
        <h2 className="register__title font-bold">Username</h2>
        <form className="register__form" onSubmit={handleSubmit}>
          <label htmlFor="">Write your name</label>
          <input
            className="register__input dark:text-gray-900 !p-2"
            type="text"
            placeholder="username"
            onChange={(e) => setUsername(e.target.value)}
          />
          <label htmlFor="">Email</label>
          <input
            className="register__input dark:text-gray-900 !p-2"
            type="text"
            placeholder="Email"
            onChange={(e) => setEmail(e.target.value)}
          />
          <label htmlFor="">Password</label>
          <input
            className="register__input dark:text-gray-900 !p-2"
            type="password"
            placeholder="Password"
            onChange={(e) => setPassword(e.target.value)}
          />
          <button className="register__button !p-2" type="submit">
           Log in
          </button>
        </form>
        <div className="register__link">You do not have a account <Link href="/login">Sign up</Link>
        </div>
        {error && <span className="register__error">Error registering!</span>}
      </div>
    </>
  );
};

export default Register;
